---
- name: Configuration - Git
  become_user: "{{ user_name }}"
  become: yes
  copy:
    src: ../files/.gitconfig
    dest: /home/{{ user_name }}/.gitconfig
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: 0644
  tags:
    - system
    - configuration

- name: Configuration - Pacman
  become: yes
  lineinfile:
    dest: /etc/pacman.conf
    regexp: "#Color"
    line: "Color"
  tags:
    - system
    - configuration

- name: Configuration - Pamac
  become: yes
  lineinfile:
    dest: /etc/pamac.conf
    regexp: "#EnableAUR"
    line: "EnableAUR"
  tags:
    - system
    - configuration

- name: Configuration - NetworkManager
  become: yes
  copy:
    src: ../files/networkmanager.conf
    dest: /etc/NetworkManager/conf.d/dns.conf
    mode: 0644
  tags:
    - system
    - configuration

- name: Configuration - dnsmasq
  become: yes
  copy:
    src: ../files/dnsmasq.conf
    dest: /etc/NetworkManager/dnsmasq.d/dns.conf
    mode: 0644
  tags:
    - system
    - configuration

- name: Configuration - Restart NetworkManager
  become: yes
  systemd:
    state: restarted
    daemon_reload: yes
    name: NetworkManager

- name: Configuration - NordNM directory
  become: yes
  become_user: '{{ user_name }}'
  file:
    path: /home/{{ user_name }}/.nordnm
    state: directory
  tags:
    - system
    - configuration

- name: Configuration - NordNM
  become: yes
  become_user: '{{ user_name }}'
  copy:
    src: ../files/nordnm-settings.conf
    dest: /home/{{ user_name }}/.nordnm/settings.conf
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: 0644
  tags:
    - system
    - configuration

- name: Configuration - Gestures
  become_user: "{{ user_name }}"
  become: yes
  copy:
    src: ../files/libinput-gestures.conf
    dest: /home/{{ user_name }}/.config/libinput-gestures.conf
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: 0644
  tags:
    - system
    - configuration
    - laptop

- name: Configuration - Reload Gestures
  become_user: "{{ user_name }}"
  become: yes
  shell: libinput-gestures-setup restart
  tags:
    - system
    - configuration
    - laptop
