---
- name: Configuration - Allow UDP for NFS
  become: yes
  lineinfile:
    dest: /etc/nfs.conf
    regexp: "udp="
    line: "udp=y"
  tags:
    - system
    - configuration

- name: Configuration - Pacman
  become: yes
  lineinfile:
    dest: /etc/pacman.conf
    regexp: "#Color"
    line: "Color"
  tags:
    - system
    - configuration

- name: Configuration - Pamac
  become: yes
  lineinfile:
    dest: /etc/pamac.conf
    regexp: "#EnableAUR"
    line: "EnableAUR"
  tags:
    - system
    - configuration

- name: Configuration - NetworkManager
  become: yes
  copy:
    src: ../files/networkmanager.conf
    dest: /etc/NetworkManager/conf.d/dns.conf
    mode: 0644
  tags:
    - system
    - configuration

- name: Configuration - dnsmasq
  become: yes
  copy:
    src: ../files/dnsmasq.conf
    dest: /etc/NetworkManager/dnsmasq.d/dns.conf
    mode: 0644
  tags:
    - system
    - configuration

- name: Configuration - Restart NetworkManager
  become: yes
  systemd:
    state: restarted
    daemon_reload: yes
    name: NetworkManager

- name: Configuration - Keychron keyboard(s)
  become: yes
  copy:
    src: ../files/keychron.conf
    dest: /etc/modprobe.d/hid_apple.conf
    mode: 0644
  tags:
    - system
    - configuration
    - desktop
