---
- name: Install system packages
  become: yes
  pacman:
    name: "{{ packages_present }}"
    state: present
  tags:
    - system

- name: Remove unwanted system packages
  become: yes
  pacman:
    name: "{{ packages_absent }}"
    state: absent
    extra_args: --recursive
  tags:
    - system

- name: Allow UDP for NFS
  become: yes
  lineinfile:
    dest: /etc/nfs.conf
    regexp: "udp="
    line: "udp=y"
  tags:
    - system

- name: Install Vagrant plugins
  become_user: "{{ user_name }}"
  become: yes
  shell: /usr/bin/vagrant plugin install {{ item }}
  loop: "{{ vagrant_plugins }}"

- include: configuration.yml
- include: laptop.yml
