---
- name: System - Install system packages
  become: yes
  pacman:
    name: "{{ packages_present }}"
    state: present
  tags:
    - system

- name: System - Remove system packages
  become: yes
  pacman:
    name: "{{ packages_absent }}"
    state: absent
    extra_args: --recursive
  tags:
    - system

- name: System - Install Vagrant plugins
  become_user: "{{ user_name }}"
  become: yes
  shell: /usr/bin/vagrant plugin install {{ item }}
  loop: "{{ vagrant_plugins }}"

- include: desktop.yml
- include: configuration.yml
