packages_present:
  - yay
  - php
  - timeshift
  - deja-dup
  - gvim
  - htop
  - neofetch
  - dnsmasq
  - base-devel
  - gamemode
  - adwaita-qt
  - papirus-icon-theme
  - ttf-fira-code
  - gnome-shell-extension-appindicator

packages_absent:
  - manjaro-ranger-settings
  - manjaro-documentation-en
  - manjaro-dynamic-wallpaper
  - manjaro-printer
  - gnome-layout-switcher
  - alacarte
  - bmenu
  - gparted
  - ranger
  - pamac-snap-plugin
  - pamac-flatpak-plugin
  - manjaro-gdm-branding
  - manjaro-gdm-theme
  - manjaro-gnome-assets
  - adwaita-maia
  - matcha-gtk-theme
  - kvantum-theme-matchama
  - xcursor-breeze
  - papirus-maia-icon-theme
  - wallpapers-2018
  - gnome-wallpapers
  - manjaro-wallpapers-18.0

vagrant_plugins:
  - vagrant-bindfs
  - vagrant-disksize
